import type { PostChannel } from "@/lib/posts/types";
import type { BoardDefinition } from "@/lib/boards/types";
import {
  isRetiredPoliticsBoard,
  POLITICS_HEATMAP_BOARD_NAV,
  TRAVEL_REGION_BOARD_NAV,
} from "@/lib/constants/nav";
import {
  CULTURE_GRANT_SEEDS,
  CULTURE_GRANT_SLUG,
  CULTURE_GRANT_TITLE,
} from "@/lib/boards/culture-grants";
import { regionalSeeds } from "@/lib/boards/regions";
import {
  EXHIBITION_BOARD_SLUG,
  HOUSING_BOARD_SLUG,
  PERFORMANCE_BOARD_SLUG,
} from "@/lib/boards/region-catalogs";
import {
  LOCAL_POLICY_SEEDS,
  PUNDIT_SEEDS,
  SUBSIDY_SEEDS,
} from "@/lib/politics/labeled-rank";

/**
 * Ranking boards: economy (headline desk + 8 boards), culture (headline + grants + boards),
 * 10 politics, 10 entertainment. Each row fixes what the board is scored from (`criteria`, fed
 * to the ranking prompt) and which affiliate shelf it pairs with, so the report
 * and the widget can never drift apart.
 */
export const BOARDS: BoardDefinition[] = [
  // ── 경제 ────────────────────────────────────────────────────────────────
  {
    id: "eco-h",
    slug: "eco-headline-news-ranking",
    channel: "economy",
    deskKind: "headlines",
    title: "헤드라인 뉴스 랭킹",
    shortTitle: "헤드라인 뉴스랭킹",
    criteria: "네이버·다음 경제 섹션과 포털 헤드라인 실시간 열독 순위",
    affiliateCategory: "경제 · 경영 서적",
    queries: ["경제 뉴스 헤드라인", "네이버 경제 많이 본 뉴스"],
    focusKeyword: "헤드라인 뉴스",
    supportKeyword: "경제 열독",
    seeds: ["금리", "환율", "부동산", "증시", "물가"],
    unitLabel: "기사",
  },
  {
    id: "eco-6",
    slug: "government-subsidy-search",
    channel: "economy",
    title: "경제 정부지원금",
    shortTitle: "경제 정부지원금",
    criteria: "중앙부처·공공기관 주관 지원금·혜택 사업의 검색·신청 관심도",
    affiliateCategory: "생필품 핫딜",
    queries: ["소상공인 대환대출", "근로장려금", "청년도약계좌", "에너지바우처", "정부 지원금 신청"],
    focusKeyword: "경제 정부지원금",
    supportKeyword: "지원 사업",
    seeds: [...SUBSIDY_SEEDS],
    rankGuidance:
      "이름은 반드시 '[소관 기관] 사업명' 형식이다. 예: [중소벤처기업부] 소상공인 대환대출, [금융위원회] 청년도약계좌. 기관명만 쓰거나 사업명만 쓰지 마라.",
    unitLabel: "사업",
  },
  {
    id: "eco-3",
    slug: "housing-subscription-hotspot",
    channel: "economy",
    title: "부동산 관심 랭킹",
    shortTitle: "부동산 관심 랭킹",
    criteria: "시/도별 아파트·전세·분양 관심도와 포털 검색·부동산 카페 언급량",
    affiliateCategory: "인테리어 · 입주 가전",
    queries: ["서울 아파트 시세", "전세 시세", "분양가 상한", "청약 경쟁률"],
    focusKeyword: "부동산 관심 랭킹",
    supportKeyword: "아파트 전세",
    rankGuidance:
      "종목명은 반드시 `[지역] 아파트 단지명` 형식이다. 지역은 서울·경기·인천·부산·대구·광주·대전·울산·세종·강원·충북·충남·전북·전남·경북·경남·제주 중 하나다. 권역·이슈명이 아니라 실제 단지명을 쓴다.",
    seeds: regionalSeeds(HOUSING_BOARD_SLUG),
    unitLabel: "단지",
  },
  {
    id: "eco-rates",
    slug: "rates-finance-products",
    channel: "economy",
    title: "금리·금융 상품",
    shortTitle: "금리·금융 상품",
    criteria: "예적금·대출·ISA 등 금리형 상품 검색량과 시중금리 뉴스",
    affiliateCategory: "경제 · 경영 서적",
    queries: ["예금 금리 비교", "주택담보대출 금리", "적금 특판", "ISA 금리"],
    focusKeyword: "금리 금융상품",
    supportKeyword: "예적금 대출",
    seeds: [
      "한국은행 기준금리",
      "코픽스",
      "주담대",
      "전세대출",
      "신용대출",
      "예금 특판",
      "적금",
      "CMA",
      "ISA",
      "청년도약계좌",
      "안심전환대출",
      "특례보금자리론",
      "소상공인 대환대출",
      "카드론",
      "리볼빙",
      "CD금리",
      "국고채",
      "RP",
      "MMF",
      "달러예금",
      "외화예금",
      "정책서민금융",
      "햇살론",
      "새희망홀씨",
      "중금리대출",
    ],
    unitLabel: "상품",
  },
  {
    id: "eco-2",
    slug: "kospi-fomo-index",
    channel: "economy",
    title: "증시·주요 종목",
    shortTitle: "증시·주요 종목",
    criteria: "코스피·코스닥 주요 종목과 서학개미 관심주의 검색·보도량",
    affiliateCategory: "트레이딩 모니터",
    queries: ["코스피 급등주", "국내 주식 시세", "엔비디아 국내 검색"],
    focusKeyword: "증시 종목",
    supportKeyword: "코스피 코스닥",
    seeds: [
      "삼성전자",
      "SK하이닉스",
      "현대차",
      "기아",
      "네이버",
      "카카오",
      "셀트리온",
      "LG에너지솔루션",
      "한화에어로스페이스",
      "삼성바이오로직스",
      "POSCO홀딩스",
      "KB금융",
      "신한지주",
      "카카오뱅크",
      "에코프로",
      "알테오젠",
      "엔비디아",
      "테슬라",
      "애플",
      "TSMC",
      "코스피",
      "코스닥",
      "환율 민감주",
      "이차전지",
      "반도체",
    ],
    unitLabel: "종목",
  },
  {
    id: "eco-fx",
    slug: "commodities-fx-index",
    channel: "economy",
    title: "원자재·환율",
    shortTitle: "원자재·환율",
    criteria: "원달러·엔화·유가·금 등 원자재·환율 검색과 시세 뉴스",
    affiliateCategory: "경제 · 경영 서적",
    queries: ["원달러 환율", "국제유가", "금 시세", "원자재 가격"],
    focusKeyword: "원자재 환율",
    supportKeyword: "유가 금",
    seeds: [
      "원달러",
      "엔화",
      "유로",
      "위안화",
      "WTI",
      "브렌트유",
      "금",
      "은",
      "구리",
      "천연가스",
      "철광석",
      "니켈",
      "리튬",
      "옥수수",
      "대두",
      "커피 원두",
      "LNG",
      "석탄",
      "알루미늄",
      "팜유",
      "환율 1400원",
      "달러인덱스",
      "엔저",
      "고유가",
      "금값",
    ],
    unitLabel: "시세",
  },
  {
    id: "eco-7",
    slug: "inflation-sentiment-index",
    channel: "economy",
    title: "소비자 물가 지수",
    shortTitle: "소비자 물가 지수",
    criteria: "밥상 물가·외식·공공요금 등 체감 물가 검색과 SNS 감성",
    affiliateCategory: "가성비 식료품 · 밀키트",
    queries: ["소비자물가", "장바구니 물가", "외식비 인상", "전기요금"],
    focusKeyword: "소비자 물가",
    supportKeyword: "체감 물가",
    seeds: [
      "외식비",
      "커피값",
      "배달비",
      "계란",
      "김치",
      "라면",
      "즉석밥",
      "농산물",
      "가공식품",
      "전기요금",
      "도시가스",
      "교통비",
      "택시비",
      "학원비",
      "병원비",
      "약값",
      "통신비",
      "아파트 관리비",
      "석유류",
      "휘발유",
      "경유",
      "소비자물가지수",
      "근원물가",
      "장바구니",
      "밀키트",
    ],
    unitLabel: "품목",
  },
  {
    id: "eco-franchise",
    slug: "startup-franchise-index",
    channel: "economy",
    title: "창업·프랜차이즈",
    shortTitle: "창업·프랜차이즈",
    criteria: "프랜차이즈·소상공인 창업 아이템 검색량과 창업 뉴스",
    affiliateCategory: "커피머신 · 에어프라이어",
    queries: ["프랜차이즈 창업", "편의점 창업", "치킨 창업 비용", "무인점포"],
    focusKeyword: "창업 프랜차이즈",
    supportKeyword: "소상공인 창업",
    seeds: [
      "편의점",
      "카페 창업",
      "치킨",
      "피자",
      "햄버거",
      "베이커리",
      "헬스장",
      "무인점포",
      "스터디카페",
      "코인세탁",
      "택배 창업",
      "밀키트 창업",
      "네일샵",
      "애견카페",
      "스크린골프",
      "학원 창업",
      "중고매장",
      "푸드트럭",
      "공유오피스",
      "숙박업",
      "배달전문",
      "가맹비",
      "창업비용",
      "소상공인 정책자금",
      "예비창업패키지",
    ],
    unitLabel: "업종",
  },
  {
    id: "eco-keywords",
    slug: "economy-issue-keywords",
    channel: "economy",
    title: "이슈 키워드",
    shortTitle: "이슈 키워드",
    criteria: "세금·규제·경기 등 경제 이슈 키워드 검색·댓글 화력",
    affiliateCategory: "경제 · 경영 서적",
    queries: ["금투세", "상속세", "부동산 세제", "환율 이슈", "물가 대책"],
    focusKeyword: "경제 이슈 키워드",
    supportKeyword: "정책 논란",
    seeds: [
      "금투세",
      "상속세",
      "증여세",
      "종합부동산세",
      "양도세",
      "법인세",
      "부가세",
      "대출규제",
      "스트레스 DSR",
      "상법 개정",
      "밸류업",
      "배당소득",
      "ISA 한도",
      "퇴직연금",
      "국민연금",
      "최저임금",
      "주4일제",
      "AI 반도체",
      "수출",
      "내수",
      "건설경기",
      "가계부채",
      "부동산 PF",
      "환율 방어",
      "추경",
    ],
    unitLabel: "키워드",
  },
  {
    id: "eco-1",
    slug: "money-youtuber-influence",
    channel: "economy",
    railHidden: true,
    title: "재테크 유튜버 영향력 랭킹",
    shortTitle: "재테크 유튜버",
    criteria: "주요 채널 조회수 및 커뮤니티 언급량 증감률",
    affiliateCategory: "유튜브 장비",
    queries: ["재테크 유튜버", "경제 유튜브 채널", "투자 유튜버 구독자"],
    focusKeyword: "재테크 유튜버",
    supportKeyword: "영향력 랭킹",
    seeds: ["슈카월드", "삼프로TV", "김짠부 재테크", "부읽남", "신사임당"],
    unitLabel: "채널",
  },
  {
    id: "eco-4",
    slug: "crypto-greed-fear",
    channel: "economy",
    railHidden: true,
    title: "크립토 탐욕/공포 랭킹",
    shortTitle: "크립토 탐욕지수",
    criteria: "비트코인 및 알트코인 거래량 및 트위터 언급량",
    affiliateCategory: "하드웨어 지갑 · 보안",
    queries: ["비트코인 시세 전망", "알트코인 거래량", "코인 투자 심리"],
    focusKeyword: "크립토 탐욕",
    supportKeyword: "코인 랭킹",
    seeds: ["비트코인", "이더리움", "리플", "솔라나", "도지코인"],
    unitLabel: "코인",
  },
  {
    id: "eco-5",
    slug: "premium-mobility-value",
    channel: "economy",
    railHidden: true,
    title: "프리미엄 모빌리티 가성비 지수",
    shortTitle: "프리미엄 모빌리티",
    criteria:
      "BMW G11 7시리즈 30만km 이상 매물, 랜드로버 디스커버리 4 등 대형 수입차의 감가상각 및 에어서스펜션(쇼바) 교체·유지비 검색 트래픽",
    affiliateCategory: "프리미엄 모빌리티",
    queries: [
      "BMW 7시리즈 중고 유지비",
      "랜드로버 디스커버리4 에어서스펜션",
      "수입 세단 감가상각 30만km",
    ],
    focusKeyword: "프리미엄 모빌리티",
    supportKeyword: "수입차 가성비",
    seeds: ["BMW 740Li G11", "디스커버리4", "에어서스펜션", "감가상각", "30만km 매물"],
    unitLabel: "차종",
  },

  // ── 문화/생활 ───────────────────────────────────────────────────────────
  {
    id: "cul-h",
    slug: "culture-headline-news-ranking",
    channel: "culture",
    deskKind: "headlines",
    title: "헤드라인 뉴스 랭킹",
    shortTitle: "헤드라인 뉴스랭킹",
    criteria: "네이버·다음 생활문화와 공연·전시·여행·맛집·레저·생활 섹션 기사만 수집한 실시간 열독·급상승 순위",
    affiliateCategory: "이북리더기 · 독서대",
    queries: ["문화 뉴스 헤드라인", "여행 맛집 레저 생활 뉴스"],
    focusKeyword: "헤드라인 뉴스",
    supportKeyword: "문화 열독",
    seeds: ["공연", "전시", "여행", "뮤지컬", "축제"],
    unitLabel: "기사",
  },
  {
    id: "cul-grant",
    slug: CULTURE_GRANT_SLUG,
    channel: "culture",
    title: CULTURE_GRANT_TITLE,
    shortTitle: CULTURE_GRANT_TITLE,
    criteria:
      "문체부·한국관광공사·문예위 등 문화·여행·레저 분야 정부·공공 지원사업의 검색·신청 관심도",
    affiliateCategory: "국내 숙박 · 나들이",
    queries: ["문화누리카드", "근로자 휴가지원", "청춘문화패스", "스포츠강좌이용권", "관광두레"],
    focusKeyword: "문화 지원금",
    supportKeyword: "여행 레저 지원",
    seeds: [...CULTURE_GRANT_SEEDS],
    rankGuidance:
      "이름은 반드시 '[주관 기관] 사업명' 형식이다. 예: [문화체육관광부 / 한국문화예술위원회] 문화누리카드, [한국관광공사] 근로자 휴가지원사업. 기관명만 쓰거나 사업명만 쓰지 마라.",
    unitLabel: "지원금",
  },
  {
    id: "cul-perf",
    slug: "performance-ticket-ranking",
    channel: "culture",
    title: "공연 랭킹",
    shortTitle: "공연 랭킹",
    criteria: "연극·뮤지컬·콘서트·클래식의 예매·검색·티켓 파워와 공연 뉴스 화제성",
    affiliateCategory: "오페라글라스 · 카메라",
    queries: ["뮤지컬 예매 순위", "콘서트 티켓팅", "연극 인기 공연", "클래식 콘서트"],
    focusKeyword: "공연 랭킹",
    supportKeyword: "티켓 파워",
    rankGuidance:
      "종목명은 반드시 `[지역] 공연/공연장` 형식이다. 지역은 서울·경기·인천·부산·대구·광주·대전·울산·세종·강원·충북·충남·전북·전남·경북·경남·제주 중 하나다.",
    seeds: regionalSeeds(PERFORMANCE_BOARD_SLUG),
    unitLabel: "공연",
  },
  {
    id: "cul-dom",
    slug: "domestic-travel-ranking",
    channel: "travel",
    title: TRAVEL_REGION_BOARD_NAV.domestic.title,
    shortTitle: TRAVEL_REGION_BOARD_NAV.domestic.shortTitle,
    criteria: "국내 도시·권역 숙박·교통 검색량과 여행 콘텐츠 화제성",
    affiliateCategory: "국내 숙박 · 나들이",
    queries: ["국내 여행지 추천", "제주 숙소", "강릉 여행", "부산 해운대"],
    focusKeyword: "국내 여행",
    supportKeyword: "국내 숙박",
    rankGuidance:
      "종목명은 반드시 `[지역] 여행지` 형식이다. 지역은 서울·경기·인천·부산·대구·광주·대전·울산·세종·강원·충북·충남·전북·전남·경북·경남·제주 중 하나다.",
    seeds: regionalSeeds("domestic-travel-ranking"),
    unitLabel: "여행지",
  },
  {
    id: "cul-over",
    slug: "overseas-travel-ranking",
    channel: "travel",
    title: "해외 여행 랭킹",
    shortTitle: "해외 여행 랭킹",
    criteria: "국가·도시별 항공권·숙소 검색량과 환율·여행 경보 뉴스",
    affiliateCategory: "캐리어 · 여행용품",
    queries: ["해외여행 인기 도시", "항공권 특가", "오사카 여행", "다낭 항공권"],
    focusKeyword: "해외 여행",
    supportKeyword: "항공권 숙소",
    seeds: [
      "일본 오사카",
      "일본 도쿄",
      "베트남 다낭",
      "태국 방콕",
      "대만 타이베이",
      "후쿠오카",
      "베트남 나트랑",
      "필리핀 세부",
      "인도네시아 발리",
      "싱가포르",
      "홍콩",
      "괌",
      "하와이",
      "유럽 파리",
      "스페인 바르셀로나",
      "이탈리아 로마",
      "체코 프라하",
      "미국 뉴욕",
      "호주 시드니",
      "몰디브",
      "오키나와",
      "치앙마이",
      "런던",
      "로스앤젤레스",
      "쿠알라룸푸르",
    ],
    unitLabel: "도시",
  },
  {
    id: "cul-out",
    slug: "weekend-outing-ranking",
    channel: "travel",
    title: TRAVEL_REGION_BOARD_NAV.outing.title,
    shortTitle: TRAVEL_REGION_BOARD_NAV.outing.shortTitle,
    criteria: "근교 공원·테마파크·도심 나들이 검색·체크인·주말 교통 관심도",
    affiliateCategory: "국내 숙박 · 나들이",
    queries: ["주말 나들이 추천", "한강공원", "에버랜드", "근교 드라이브"],
    focusKeyword: "주말 나들이",
    supportKeyword: "근교 나들이",
    rankGuidance:
      "종목명은 반드시 `[지역] 나들이 장소` 형식이다. 지역은 서울·경기·인천·부산·대구·광주·대전·울산·세종·강원·충북·충남·전북·전남·경북·경남·제주 중 하나다.",
    seeds: regionalSeeds("weekend-outing-ranking"),
    unitLabel: "장소",
  },
  {
    id: "cul-ex",
    slug: "exhibition-popup-ranking",
    channel: "culture",
    title: "전시·팝업스토어",
    shortTitle: "전시·팝업스토어",
    criteria: "미술관·몰입형 전시·브랜드 팝업의 예약·오픈런·SNS 언급량",
    affiliateCategory: "삼각대 · 보조배터리",
    queries: ["서울 전시회 추천", "성수 팝업스토어", "몰입형 전시", "더현대 팝업"],
    focusKeyword: "전시 팝업",
    supportKeyword: "오픈런",
    rankGuidance:
      "종목명은 반드시 `[지역] 전시/팝업` 형식이다. 지역은 서울·경기·인천·부산·대구·광주·대전·울산·세종·강원·충북·충남·전북·전남·경북·경남·제주 중 하나다.",
    seeds: regionalSeeds(EXHIBITION_BOARD_SLUG),
    unitLabel: "전시",
  },
  {
    id: "cul-3",
    slug: "bestseller-surge-index",
    channel: "culture",
    title: "도서·베스트셀러",
    shortTitle: "도서·베스트셀러",
    criteria: "대형 서점 실시간 검색어 및 도서 리뷰·베스트셀러 변동",
    affiliateCategory: "이북리더기 · 독서대",
    queries: ["베스트셀러 순위", "서점 화제의 책", "신간 도서 리뷰"],
    focusKeyword: "도서 베스트셀러",
    supportKeyword: "급상승 도서",
    seeds: [
      "마흔에 읽는 쇼펜하우어",
      "세이노의 가르침",
      "역행자",
      "도둑맞은 집중력",
      "트렌드 코리아",
      "불편한 편의점",
      "채식주의자",
      "작별하지 않는다",
      "사피엔스",
      "코스모스",
      "미움받을 용기",
      "데일 카네기",
      "어린왕자",
      "데미안",
      "자존감 수업",
      "달러구트 꿈 백화점",
      "부의 추월차선",
      "돈의 심리학",
      "1984",
      "총균쇠",
      "원피스",
      "해리포터",
      "조선의 오후",
      "오만과 편견",
      "나미야 잡화점",
    ],
    unitLabel: "도서",
  },
  {
    id: "cul-health",
    slug: "health-info-ranking",
    channel: "culture",
    title: "건강정보 랭킹",
    shortTitle: "건강정보 랭킹",
    criteria: "건강검진·질환 키워드 검색량과 건강 콘텐츠 화제성",
    affiliateCategory: "건강기능식품 · 영양제",
    queries: ["건강검진 항목", "혈압 혈당 관리", "독감 예방접종", "임플란트"],
    focusKeyword: "건강정보",
    supportKeyword: "검진 키워드",
    seeds: [
      "혈압",
      "혈당",
      "콜레스테롤",
      "간수치",
      "갑상선",
      "위내시경",
      "대장내시경",
      "독감 예방접종",
      "대상포진 백신",
      "건강검진",
      "수면무호흡",
      "허리디스크",
      "무릎연골",
      "안과 백내장",
      "치과 임플란트",
      "피부과 보톡스",
      "한의원 추나",
      "산부인과 정기검진",
      "소아과 성장",
      "정신건강의학과",
      "골다공증",
      "통풍",
      "당뇨합병증",
      "전립선",
      "갱년기",
    ],
    unitLabel: "키워드",
  },
  {
    id: "cul-recipe",
    slug: "recipe-ranking",
    channel: "culture",
    title: "요리 레시피 랭킹",
    shortTitle: "요리 레시피 랭킹",
    criteria: "집밥·밀키트·에어프라이어 레시피 검색량과 요리 콘텐츠 화제성",
    affiliateCategory: "커피머신 · 에어프라이어",
    queries: ["김치찌개 레시피", "에어프라이어 요리", "집밥 메뉴", "초보 요리"],
    focusKeyword: "요리 레시피",
    supportKeyword: "집밥 검색",
    seeds: [
      "김치찌개",
      "된장찌개",
      "순두부찌개",
      "제육볶음",
      "불고기",
      "잡채",
      "비빔밥",
      "김밥",
      "떡볶이",
      "라면",
      "파스타",
      "스테이크",
      "샐러드",
      "샌드위치",
      "에어프라이어 치킨",
      "에어프라이어 고구마",
      "에어프라이어 만두",
      "전자레인지 계란찜",
      "계란말이",
      "오므라이스",
      "갈비찜",
      "삼겹살",
      "부대찌개",
      "카레",
      "볶음밥",
    ],
    unitLabel: "레시피",
  },
  {
    id: "cul-car",
    slug: "car-review-ranking",
    channel: "culture",
    title: "자동차/시승기 랭킹",
    shortTitle: "자동차/시승기 랭킹",
    criteria: "신차·전기차 시승기 조회와 차종 검색·커뮤니티 화제성",
    affiliateCategory: "프리미엄 모빌리티",
    queries: ["아이오닉6 시승기", "EV3 후기", "그랜저 페이스리프트", "전기차 비교"],
    focusKeyword: "자동차 시승기",
    supportKeyword: "신차 화제",
    seeds: [
      "아이오닉6",
      "EV3",
      "EV9",
      "아이오닉5",
      "테슬라 모델Y",
      "테슬라 모델3",
      "그랜저",
      "쏘나타",
      "아반떼",
      "카니발",
      "스포티지",
      "싼타페",
      "팰리세이드",
      "BMW 5시리즈",
      "벤츠 E클래스",
      "아우디 A6",
      "볼보 XC60",
      "렉서스 ES",
      "포르쉐 타이칸",
      "제네시스 GV80",
      "캐스퍼",
      "레이",
      "코나",
      "투싼",
      "XM3",
    ],
    unitLabel: "차종",
  },
  {
    id: "cul-food",
    slug: "food-restaurant-ranking",
    channel: "travel",
    title: TRAVEL_REGION_BOARD_NAV.food.title,
    shortTitle: TRAVEL_REGION_BOARD_NAV.food.shortTitle,
    criteria: "지역별 맛집·대표 음식 검색량과 미식 콘텐츠 화제성",
    affiliateCategory: "가성비 식료품 · 밀키트",
    queries: ["서울 맛집", "부산 밀면", "전주 비빔밥", "제주 흑돼지"],
    focusKeyword: "음식 맛집",
    supportKeyword: "지역 맛집",
    rankGuidance:
      "종목명은 반드시 `[지역] 상호/음식` 형식이다. 지역은 서울·경기·인천·부산·대구·광주·대전·울산·세종·강원·충북·충남·전북·전남·경북·경남·제주 중 하나다.",
    seeds: regionalSeeds("food-restaurant-ranking"),
    unitLabel: "맛집",
  },
  {
    id: "cul-issue",
    slug: "culture-issue-keywords",
    channel: "culture",
    title: "이슈 키워드",
    shortTitle: "이슈 키워드",
    criteria: "공연 취소·오버투어리즘·문화패스 등 문화 이슈 검색·댓글 화력",
    affiliateCategory: "이북리더기 · 독서대",
    queries: ["문화패스", "오버투어리즘", "공연 취소", "팝업 오픈런"],
    focusKeyword: "문화 이슈",
    supportKeyword: "이슈 키워드",
    seeds: [
      "문화패스",
      "청춘문화패스",
      "오버투어리즘",
      "공연 취소",
      "티켓팅 먹통",
      "팝업 오픈런",
      "야간개장",
      "혼행",
      "워케이션",
      "글램핑",
      "템플스테이",
      "한복 체험",
      "지역축제",
      "한강 벚꽃",
      "얼리버드 티켓",
      "K-컬처",
      "무장애 여행",
      "캠핑카",
      "독서 챌린지",
      "뮤지컬 캐스팅",
      "공연 매진",
      "암표",
      "페스티벌",
      "날씨 예매",
      "실내 공연",
    ],
    unitLabel: "키워드",
  },
  {
    id: "cul-1",
    slug: "ott-buzz-ranking",
    channel: "culture",
    railHidden: true,
    title: "OTT 통합 화제성 랭킹",
    shortTitle: "OTT 화제성",
    criteria: "넷플릭스, 디즈니+ 등 최신작 커뮤니티 리뷰 수",
    affiliateCategory: "스마트TV · 사운드바",
    queries: ["넷플릭스 인기 시리즈", "디즈니플러스 신작", "OTT 드라마 반응"],
    focusKeyword: "OTT 화제작",
    supportKeyword: "화제성 랭킹",
    seeds: ["넷플릭스 신작", "티빙 오리지널", "디즈니+ 시리즈", "쿠팡플레이", "웨이브"],
    unitLabel: "작품",
  },
  {
    id: "cul-2",
    slug: "hotplace-visit-index",
    channel: "culture",
    railHidden: true,
    title: "전국 핫플레이스 방문 지수",
    shortTitle: "핫플레이스",
    criteria: "인스타그램/블로그 지역 태그 및 체크인 순위",
    affiliateCategory: "삼각대 · 보조배터리",
    queries: ["핫플레이스 추천", "인스타 성지 여행", "주말 나들이 명소"],
    focusKeyword: "핫플레이스",
    supportKeyword: "방문 지수",
    seeds: ["성수동", "연남동", "해운대", "전주 한옥마을", "강릉"],
    unitLabel: "지역",
  },
  {
    id: "cul-5",
    slug: "fnb-trend-ranking",
    channel: "culture",
    railHidden: true,
    title: "F&B 트렌드 급상승 랭킹",
    shortTitle: "F&B 트렌드",
    criteria: "흑백요리사 등 요리/맛집 키워드 검색량",
    affiliateCategory: "커피머신 · 에어프라이어",
    queries: ["맛집 트렌드", "요리 예능 화제", "디저트 유행"],
    focusKeyword: "F&B 트렌드",
    supportKeyword: "미식 랭킹",
    seeds: ["흑백요리사", "오마카세", "베이글", "두바이 초콜릿", "하이볼"],
    unitLabel: "키워드",
  },
  {
    id: "cul-7",
    slug: "lifestyle-hip-index",
    channel: "culture",
    railHidden: true,
    title: "라이프스타일/패션 힙 지수",
    shortTitle: "패션 힙 지수",
    criteria: "시즌별 패션 아이템 및 뷰티 트렌드 언급량",
    affiliateCategory: "시즌 의류 · 뷰티",
    queries: ["패션 트렌드", "뷰티 신상", "시즌 코디 유행"],
    focusKeyword: "패션 트렌드",
    supportKeyword: "힙 지수",
    seeds: ["고프코어", "발레코어", "글로시 메이크업", "테니스룩", "빈티지 데님"],
    unitLabel: "아이템",
  },

  // ── 정치 ────────────────────────────────────────────────────────────────
  {
    id: "pol-h",
    slug: "headline-news-ranking",
    channel: "politics",
    deskKind: "headlines",
    title: "헤드라인 뉴스 랭킹",
    shortTitle: "헤드라인 뉴스랭킹",
    criteria: "네이버·다음 정치 섹션과 포털 헤드라인 실시간 열독 순위",
    affiliateCategory: "시사 주간지",
    queries: ["정치 뉴스 헤드라인", "네이버 정치 많이 본 뉴스"],
    focusKeyword: "헤드라인 뉴스",
    supportKeyword: "정치 열독",
    seeds: ["국회", "대통령", "여야", "지지율", "외교"],
    unitLabel: "기사",
  },
  {
    id: "pol-pc",
    slug: "party-support-chart",
    channel: "politics",
    title: POLITICS_HEATMAP_BOARD_NAV["party-support-chart"].title,
    shortTitle: POLITICS_HEATMAP_BOARD_NAV["party-support-chart"].shortTitle,
    criteria: "한국갤럽·리얼미터·NBS 전국지표조사 최근 6개월 정당 지지도",
    affiliateCategory: "정치학 개론",
    queries: ["정당 지지율 여론조사", "한국갤럽 정당 지지도", "NBS 정당"],
    focusKeyword: "정당 지지도",
    supportKeyword: "여론조사",
    seeds: [
      "더불어민주당",
      "국민의힘",
      "조국혁신당",
      "개혁신당",
      "진보당",
      "기본소득당",
      "사회민주당",
      "정의당",
      "새로운미래",
      "무소속",
      "국민의당",
      "열린민주당",
      "시대전환",
      "녹색당",
      "민생당",
    ],
    unitLabel: "정당",
  },
  {
    id: "pol-ic",
    slug: "politician-support-chart",
    channel: "politics",
    title: POLITICS_HEATMAP_BOARD_NAV["politician-support-chart"].title,
    shortTitle: POLITICS_HEATMAP_BOARD_NAV["politician-support-chart"].shortTitle,
    criteria: "한국갤럽·리얼미터·NBS 전국지표조사 최근 6개월 주요 정치인 지지도",
    affiliateCategory: "정치 에세이",
    queries: ["정치인 지지율 여론조사", "대통령 지지도 갤럽", "차기 대선주자 지지도"],
    focusKeyword: "정치인 지지도",
    supportKeyword: "여론조사",
    seeds: [
      "이재명",
      "한동훈",
      "오세훈",
      "이준석",
      "조국",
      "김문수",
      "김동연",
      "박찬대",
      "배현진",
      "정청래",
      "홍준표",
      "안철수",
      "원희룡",
      "나경원",
      "이낙연",
      "심상정",
      "김기현",
      "고민정",
      "추미애",
      "우원식",
      "김민석",
      "박용진",
      "장동혁",
      "송언석",
      "강훈식",
    ],
    unitLabel: "인물",
  },
  {
    id: "pol-6",
    slug: "governor-approval-index",
    channel: "politics",
    title: "지자체 정책지수",
    shortTitle: "지자체 정책지수",
    criteria: "광역·기초 지자체의 화제 성공 정책 검색·보도량과 호응",
    affiliateCategory: "건강기능식품 · 영양제",
    queries: ["기후동행카드", "청년월세 지원", "100원 택시", "새빛돌봄", "지자체 정책 호응"],
    focusKeyword: "지자체 정책지수",
    supportKeyword: "성공 정책",
    seeds: [...LOCAL_POLICY_SEEDS],
    rankGuidance:
      "이름은 반드시 '[지자체명] 정책명' 형식이다. 예: [서울특별시] 기후동행카드, [경기도 수원시] 새빛돌봄, [전라남도] 100원 택시. 지자체장 이름만 쓰지 마라.",
    unitLabel: "정책",
  },
  {
    id: "pol-8",
    slug: "government-support-fund",
    channel: "politics",
    title: "정부 지원금",
    shortTitle: "정부 지원금",
    criteria: "중앙부처·지자체 주관 지원금·혜택 사업의 검색·신청 관심도",
    affiliateCategory: "생필품 핫딜",
    queries: ["청년도약계좌", "소상공인 전기요금 지원", "근로장려금", "부모급여", "정부 지원금 신청"],
    focusKeyword: "정부 지원금",
    supportKeyword: "지원 사업",
    seeds: [...SUBSIDY_SEEDS],
    rankGuidance:
      "이름은 반드시 '[소관 기관] 사업명' 형식이다. 예: [금융위원회] 청년도약계좌, [중소벤처기업부] 소상공인 전기요금 지원.",
    unitLabel: "사업",
  },
  {
    id: "pol-4",
    slug: "political-influencer-power",
    channel: "politics",
    title: "정치 인기 유튜브 랭킹",
    shortTitle: "정치 인기 유튜브 랭킹",
    criteria: "정치·시사 유튜브 채널의 조회·라이브·뉴스 인용",
    affiliateCategory: "블루투스 이어폰",
    queries: ["정치 유튜버", "시사 유튜브 채널", "정치 방송 화제"],
    focusKeyword: "정치 인기 유튜브",
    supportKeyword: "유튜브 랭킹",
    seeds: [
      "김어준의 겸손은 힘들다 뉴스공장",
      "김용민TV",
      "가로세로연구소",
      "신의한수",
      "딴지방송국",
      "펜앤드마이크",
      "매불쇼",
      "이봉규TV",
    ],
    rankGuidance:
      "유튜브 대형 시사 채널은 뉴스/미디어로 분류돼도 반드시 포함한다. '김어준의 겸손은 힘들다 뉴스공장'은 1위권 고정 후보이며 이름을 줄이거나 빼지 마라.",
    unitLabel: "채널",
  },
  {
    id: "pol-9",
    slug: "political-pundit-ranking",
    channel: "politics",
    title: "정치평론가 랭킹",
    shortTitle: "정치평론가 랭킹",
    criteria: "시사·정치 평론가의 방송 출연·칼럼·발언 인용량",
    affiliateCategory: "시사 주간지",
    queries: ["시사평론가", "정치 평론가 발언", "시사 토론 출연"],
    focusKeyword: "정치평론가",
    supportKeyword: "평론 랭킹",
    seeds: [...PUNDIT_SEEDS],
    rankGuidance:
      "이름은 반드시 '인물명 (활동 매체/직함)' 형식이다. 예: 유시민 (알릴레오), 진중권 (시사평론가), 김종배 (시사자키). 유튜브 채널명은 정치 인기 유튜브 랭킹 보드에만 둔다.",
    unitLabel: "평론가",
  },
  {
    id: "pol-5",
    slug: "policy-controversy-index",
    channel: "politics",
    title: "핵심 정책·이슈 키워드 지수",
    shortTitle: "이슈 키워드",
    criteria: "세금, 연금 개혁 등 정책 키워드 댓글 화력",
    affiliateCategory: "경제 · 경영 서적",
    queries: ["부동산 정책 논란", "세금 개편", "연금 개혁 반발"],
    focusKeyword: "이슈 키워드",
    supportKeyword: "정책 논란",
    seeds: ["종합부동산세", "연금개혁", "상속세", "의대 정원", "전세제도"],
    unitLabel: "키워드",
  },
  {
    id: "pol-1",
    slug: "politician-buzz-index",
    channel: "politics",
    railHidden: true,
    title: "주요 정치인 화제성 지수",
    shortTitle: "정치인 화제성",
    criteria: "포털 메인 노출 빈도 및 기사 댓글 수 총합 순위",
    affiliateCategory: "정치 · 역사 도서",
    queries: ["정치인 여론", "정치인 지지율", "국회의원 발언 논란"],
    focusKeyword: "정치인 화제성",
    supportKeyword: "화제성 지수",
    seeds: ["이재명", "한동훈", "조국", "오세훈", "홍준표"],
    unitLabel: "인물",
  },
  {
    id: "pol-2",
    slug: "party-sentiment-index",
    channel: "politics",
    railHidden: true,
    title: "주요 정당 호감/비호감 지수",
    shortTitle: "정당 호감도",
    criteria: "각 정당 관련 기사 및 커뮤니티 감성 분석 비율",
    affiliateCategory: "안마기 · 릴랙스",
    queries: ["정당 지지율", "여야 여론조사", "정당 이미지 평가"],
    focusKeyword: "정당 호감도",
    supportKeyword: "정당 지지율",
    seeds: ["더불어민주당", "국민의힘", "조국혁신당", "개혁신당", "진보당"],
    unitLabel: "정당",
  },
  {
    id: "pol-3",
    slug: "assembly-bill-attention",
    channel: "politics",
    railHidden: true,
    title: "국회 쟁점 법안 관심도 랭킹",
    shortTitle: "쟁점 법안",
    criteria: "여야 대립 법안 및 민생 법안 검색 트래픽 순위",
    affiliateCategory: "사무용품 · 데스크테리어",
    queries: ["국회 쟁점 법안", "본회의 처리 법안", "민생 법안 논의"],
    focusKeyword: "쟁점 법안",
    supportKeyword: "국회 관심도",
    seeds: ["예산안", "노란봉투법", "연금개혁안", "부동산세제", "AI 기본법"],
    unitLabel: "법안",
  },
  {
    id: "pol-7",
    slug: "global-risk-index",
    channel: "politics",
    railHidden: true,
    title: "글로벌 외교/안보 리스크 지수",
    shortTitle: "외교안보 리스크",
    criteria: "미국 대선, 국제 분쟁 관련 국내 포털 검색량",
    affiliateCategory: "캠핑 · 생존 용품",
    queries: ["국제 정세 한국 영향", "외교 안보 현안", "미국 정책 한국"],
    focusKeyword: "외교 안보 리스크",
    supportKeyword: "글로벌 리스크",
    seeds: ["미국 대선", "한미동맹", "북한 도발", "중동 정세", "관세 정책"],
    unitLabel: "이슈",
  },

  // ── 엔터테인먼트 ─────────────────────────────────────────────────────────
  {
    id: "ent-h",
    slug: "ent-headline-news-ranking",
    channel: "entertainment",
    deskKind: "headlines",
    title: "헤드라인 뉴스 랭킹",
    shortTitle: "헤드라인 뉴스랭킹",
    criteria: "네이버·다음 연예 섹션과 포털 헤드라인 실시간 열독 순위",
    affiliateCategory: "무선 이어폰 · 헤드폰",
    queries: ["연예 뉴스 헤드라인", "네이버 연예 많이 본 뉴스"],
    focusKeyword: "헤드라인 뉴스",
    supportKeyword: "연예 열독",
    seeds: ["아이돌", "드라마", "예능", "컴백", "시상식"],
    unitLabel: "기사",
  },
  {
    id: "ent-2",
    slug: "realtime-music-chart",
    channel: "entertainment",
    title: "실시간 음원 차트",
    shortTitle: "실시간 음원 차트",
    criteria: "멜론·지니·벅스·스포티파이 코리아 실시간 차트 진입과 검색·숏폼 사운드 확산",
    affiliateCategory: "무선 이어폰 · 헤드폰",
    queries: ["멜론 실시간 차트", "스포티파이 코리아 차트", "음원 차트 1위", "아이돌 신곡 음원"],
    focusKeyword: "실시간 음원 차트",
    supportKeyword: "음원 순위",
    seeds: [
      "APT. 로제",
      "뛰어 BLACKPINK",
      "Whiplash 에스파",
      "첫 만남은 계획대로 되지 않아",
      "Super Shy 뉴진스",
      "Seven 정국",
      "해야 IVE",
      "나는 반딧불",
      "HOME SWEET HOME",
      "Ditto 뉴진스",
      "Love wins all 아이유",
      "Spot! 지코",
      "Magnetic 아일릿",
      "How Sweet 뉴진스",
      "Supernova 에스파",
      "클락션 (Klaxon)",
      "Small girl 이영지",
      "Cherish 에스파",
      "Sticky KISS OF LIFE",
      "Armageddon 에스파",
      "Should Be 세븐틴",
      "Impossible 린",
      "나는 아픈 건 딱 질색이니까",
      "Love 119",
      "To. X 태연",
      "Drama 에스파",
      "Get A Guitar 라이즈",
      "Perfect Night 르세라핌",
    ],
    unitLabel: "곡",
    rankGuidance:
      "반드시 실제 음원 곡명(가수명 포함)만 적어라. '음원 A' 같은 플레이스홀더는 금지. 10대는 아이돌 타이틀곡, 40대 이상은 발라드·트로트 리메이크 비중을 높여라.",
    demographicSeeds: {
      age: {
        "10s": ["해야 IVE", "Magnetic 아일릿", "How Sweet 뉴진스", "Whiplash 에스파", "Get A Guitar 라이즈", "Perfect Night 르세라핌"],
        "20s": ["APT. 로제", "Seven 정국", "HOME SWEET HOME", "Small girl 이영지", "Sticky KISS OF LIFE"],
        "30s": ["Love wins all 아이유", "Spot! 지코", "To. X 태연", "Impossible 린"],
        "40s": ["Love wins all 아이유", "Impossible 린", "나는 아픈 건 딱 질색이니까", "To. X 태연"],
        "50s": ["Impossible 린", "Love wins all 아이유", "나는 반딧불", "To. X 태연"],
        "60s": ["Impossible 린", "나는 반딧불", "Love wins all 아이유"],
        "70s": ["Impossible 린", "나는 반딧불", "Love 119"],
      },
    },
  },
  {
    id: "ent-1",
    slug: "kpop-fandom-power",
    channel: "entertainment",
    title: "K-Pop 아이돌 팬덤 화력 지수",
    shortTitle: "아이돌 팬덤 화력",
    criteria: "차트 진입·팬덤 총공·콘서트 수요. 현역 K-POP 아이돌 화력만 집계한다",
    affiliateCategory: "무선 이어폰 · 헤드폰",
    queries: ["아이돌 컴백 반응", "케이팝 차트 순위", "팬덤 화력", "아이돌 콘서트 티켓팅"],
    focusKeyword: "아이돌 팬덤",
    supportKeyword: "팬덤 화력",
    seeds: [
      "아이브",
      "뉴진스",
      "세븐틴",
      "에스파",
      "BTS",
      "블랙핑크",
      "르세라핌",
      "스트레이 키즈",
      "라이즈",
      "투어스",
      "보이넥스트도어",
      "아일릿",
      "베이비몬스터",
      "TXT",
      "엔하이픈",
      "NCT 드림",
      "NCT 127",
      "(여자)아이들",
      "aespa",
      "ZEROBASEONE",
      "TWS",
      "NCT WISH",
      "ILLIT",
      "KISS OF LIFE",
      "NEXZ",
      "아이유",
    ],
    unitLabel: "그룹",
    rankGuidance:
      "현역 K-POP 아이돌·그룹만 적어라. 임영웅·영탁·이찬원·김호중·송가인 등 트로트 가수는 이 보드에 넣지 마라. 10대·20대·30대 관심 차이를 반영하되, 모두 아이돌 권역 안에 둬라.",
    demographicSeeds: {
      age: {
        "10s": ["아이브", "뉴진스", "에스파", "르세라핌", "아일릿", "베이비몬스터", "라이즈", "투어스", "보이넥스트도어", "TXT"],
        "20s": ["세븐틴", "스트레이 키즈", "엔하이픈", "NCT 드림", "BTS", "블랙핑크", "아이브", "에스파"],
        "30s": ["BTS", "블랙핑크", "세븐틴", "아이유", "빅뱅", "동방신기"],
      },
    },
    demographicExclude: {
      always: [
        "임영웅",
        "영탁",
        "이찬원",
        "김호중",
        "송가인",
        "나훈아",
        "장민호",
        "정동원",
        "주현미",
        "심수봉",
        "태진아",
        "조용필",
        "이미자",
      ],
      age: {
        "10s": ["임영웅", "영탁", "이찬원", "김호중", "송가인", "나훈아"],
        "20s": ["임영웅", "영탁", "이찬원", "김호중", "송가인", "나훈아"],
        "30s": ["임영웅", "영탁", "이찬원", "김호중", "송가인", "나훈아"],
      },
    },
  },
  {
    id: "ent-9",
    slug: "trot-kayo-fandom-power",
    channel: "entertainment",
    title: "트로트·가요 팬덤 화력 지수",
    shortTitle: "트로트·가요 팬덤 화력",
    criteria: "트로트·성인가요·7080 가수의 콘서트·음원·팬클럽 화력",
    affiliateCategory: "무선 이어폰 · 헤드폰",
    queries: ["임영웅 콘서트", "미스터트롯 가수", "트로트 가수 인기", "성인가요 콘서트", "7080 가수"],
    focusKeyword: "트로트 팬덤",
    supportKeyword: "가요 화력",
    seeds: [
      "임영웅",
      "영탁",
      "이찬원",
      "김호중",
      "송가인",
      "장민호",
      "정동원",
      "나훈아",
      "심수봉",
      "주현미",
      "태진아",
      "조용필",
      "이미자",
      "설운도",
      "진성",
      "신유",
      "황치열",
      "김용임",
      "김연자",
      "패티김",
      "조항조",
      "장윤정",
      "박현빈",
      "김수찬",
      "금잔디",
      "강진",
      "현숙",
      "김혜연",
    ],
    unitLabel: "가수",
    rankGuidance:
      "트로트·성인가요·7080 가수만 적어라. 아이브·뉴진스·에스파 등 현역 K-POP 아이돌은 이 보드에 넣지 마라. 40대부터 70대 이상 팬덤 차이를 반영하라.",
    demographicSeeds: {
      age: {
        "40s": ["임영웅", "영탁", "이찬원", "장윤정", "박현빈", "황치열", "김호중"],
        "50s": ["임영웅", "영탁", "이찬원", "김호중", "송가인", "장민호", "정동원", "나훈아"],
        "60s": ["임영웅", "나훈아", "송가인", "심수봉", "주현미", "태진아", "조용필", "이미자"],
        "70s": ["나훈아", "조용필", "이미자", "심수봉", "주현미", "태진아", "패티김", "김연자"],
      },
    },
    demographicExclude: {
      always: ["아이브", "뉴진스", "에스파", "르세라핌", "라이즈", "BTS", "블랙핑크", "세븐틴", "스트레이 키즈", "아일릿"],
      age: {
        "40s": ["아이브", "뉴진스", "에스파", "르세라핌", "라이즈"],
        "50s": ["아이브", "뉴진스", "에스파", "르세라핌", "라이즈"],
        "60s": ["아이브", "뉴진스", "에스파", "르세라핌", "라이즈"],
        "70s": ["아이브", "뉴진스", "에스파", "르세라핌", "라이즈"],
      },
    },
  },
  {
    id: "ent-3",
    slug: "realtime-tv-ratings",
    channel: "entertainment",
    title: "실시간 시청률 순위",
    shortTitle: "실시간 시청률 순위",
    criteria: "지상파·종편·케이블 실시간 시청률과 동시간대 화제성",
    affiliateCategory: "태블릿PC · 거치대",
    queries: ["실시간 시청률", "드라마 시청률", "예능 시청률", "뉴스 시청률", "닐슨 시청률"],
    focusKeyword: "실시간 시청률",
    supportKeyword: "시청률 순위",
    seeds: [
      "KBS 뉴스9",
      "MBC 뉴스데스크",
      "SBS 8뉴스",
      "나 혼자 산다",
      "미운 우리 새끼",
      "런닝맨",
      "유 퀴즈 온 더 블럭",
      "진격의 할매",
      "나는 솔로",
      "하트시그널",
      "선재 업고 튀어",
      "눈물의 여왕",
      "여보 미안해",
      "핑계고",
      "전국노래자랑",
      "열린음악회",
      "불후의 명곡",
      "1박 2일",
      "신랑수업",
      "동상이몽",
      "오은영 리포트",
      "뉴스A",
      "JTBC 뉴스룸",
      "TV조선 뉴스",
      "그것이 알고싶다",
      "스우파",
      "흑백요리사",
      "쇼! 음악중심",
    ],
    unitLabel: "프로그램",
    rankGuidance:
      "실제 방송 프로그램명만 사용하라. 시청률 조사 대상인 뉴스·드라마·예능을 섞되, '프로그램 A' 같은 플레이스홀더는 금지. 10대는 아이돌 서바이벌·연애 예능, 50대 이상은 뉴스·전국노래자랑·불후의 명곡 비중을 높여라.",
    demographicSeeds: {
      age: {
        "10s": ["스우파", "하트시그널", "나는 솔로", "쇼! 음악중심", "선재 업고 튀어"],
        "20s": ["나 혼자 산다", "흑백요리사", "하트시그널", "눈물의 여왕", "런닝맨"],
        "30s": ["유 퀴즈 온 더 블럭", "나 혼자 산다", "그것이 알고싶다", "미운 우리 새끼"],
        "40s": ["미운 우리 새끼", "KBS 뉴스9", "MBC 뉴스데스크", "1박 2일"],
        "50s": ["KBS 뉴스9", "MBC 뉴스데스크", "불후의 명곡", "미운 우리 새끼", "전국노래자랑"],
        "60s": ["전국노래자랑", "열린음악회", "불후의 명곡", "KBS 뉴스9"],
        "70s": ["전국노래자랑", "열린음악회", "KBS 뉴스9", "불후의 명곡"],
      },
    },
  },
  {
    id: "ent-4",
    slug: "star-reputation-index",
    channel: "entertainment",
    title: "스타/배우 브랜드 평판 지수",
    shortTitle: "스타 브랜드 평판",
    criteria: "광고 모델 기용 및 인터뷰/화보 검색량 순위",
    affiliateCategory: "패션 악세사리 · 향수",
    queries: ["배우 광고 모델", "스타 브랜드 평판", "연예인 화보", "아이돌 화보 평판"],
    focusKeyword: "스타 브랜드 평판",
    supportKeyword: "배우 평판",
    seeds: [
      "장원영",
      "카리나",
      "안유진",
      "해린",
      "윈터",
      "김지원",
      "노윤서",
      "문가영",
      "고윤정",
      "변우석",
      "채종협",
      "이재욱",
      "손석구",
      "김고은",
      "한소희",
      "마동석",
      "아이유",
      "수지",
      "박보검",
      "현빈",
      "손예진",
      "공유",
      "전지현",
      "이정재",
      "김수현",
      "임영웅",
      "송가인",
      "나문희",
    ],
    unitLabel: "인물",
    rankGuidance:
      "10대 여성 1위는 장원영·카리나·안유진·해린·윈터 등 현역 아이돌 또는 또래 배우여야 한다. 임영웅·영탁·이찬원·김호중을 10대·20대 선두에 올리는 것은 오류다. 50대 이상은 중견 배우와 트로트 스타가 자연스럽다.",
    demographicSeeds: {
      gender: {
        female: ["장원영", "카리나", "안유진", "해린", "윈터", "김지원", "노윤서", "고윤정", "아이유", "수지", "김고은", "한소희"],
        male: ["변우석", "채종협", "이재욱", "손석구", "박보검", "현빈", "공유", "김수현", "마동석", "이정재"],
      },
      age: {
        "10s": ["장원영", "카리나", "안유진", "해린", "윈터", "닝닝", "민지", "김지원", "노윤서", "문가영", "변우석", "채종협"],
        "20s": ["카리나", "장원영", "고윤정", "한소희", "변우석", "이재욱", "아이유", "문가영"],
        "30s": ["김고은", "손석구", "수지", "공유", "박보검"],
        "40s": ["현빈", "손예진", "마동석", "전지현", "이정재"],
        "50s": ["이정재", "나문희", "임영웅", "송가인", "마동석"],
        "60s": ["나문희", "최불암", "이순재", "임영웅", "송가인"],
        "70s": ["이순재", "최불암", "나문희", "고두심"],
      },
    },
    demographicExclude: {
      age: {
        "10s": ["임영웅", "영탁", "이찬원", "김호중", "송가인", "나훈아", "태진아", "나문희", "최불암", "이순재"],
        "20s": ["임영웅", "영탁", "이찬원", "김호중", "나훈아", "태진아", "나문희", "최불암", "이순재"],
      },
    },
  },
  {
    id: "ent-5",
    slug: "game-esports-ranking",
    channel: "entertainment",
    title: "게임/e스포츠 인기 랭킹",
    shortTitle: "게임 e스포츠",
    criteria: "PC방 점유율 및 치지직/숲(SOOP) 시청자 수",
    affiliateCategory: "게이밍 기어",
    queries: ["PC방 점유율", "e스포츠 경기 화제", "게임 스트리밍 시청자", "스팀 인기 게임"],
    focusKeyword: "게임 인기",
    supportKeyword: "e스포츠 랭킹",
    seeds: [
      "리그 오브 레전드",
      "발로란트",
      "배틀그라운드",
      "FC 온라인",
      "메이플스토리",
      "오버워치 2",
      "로블록스",
      "마인크래프트",
      "원신",
      "젠지",
      "T1",
      "한화생명",
      "스팀 대작",
      "던전앤파이터",
      "로스트아크",
      "서든어택",
      "스타크래프트",
      "카트라이더",
      "쿠키런",
      "브롤스타즈",
      "포켓몬 유나이트",
      "디아블로",
      "패스 오브 엑자일",
      "엘든링",
      "GTA",
      "동물의 숲",
      "젤다의 전설",
      "닌텐도 스위치",
    ],
    unitLabel: "게임",
    rankGuidance:
      "10대는 로블록스·브롤스타즈·마인크래프트, 20~30대는 LOL·발로란트·배그, 40대 이상은 FC온라인·스타크래프트 향수를 반영하라. 실제 게임/팀명만 사용하라.",
    demographicSeeds: {
      age: {
        "10s": ["로블록스", "마인크래프트", "브롤스타즈", "쿠키런", "포켓몬 유나이트", "원신"],
        "20s": ["리그 오브 레전드", "발로란트", "배틀그라운드", "원신", "T1", "젠지"],
        "40s": ["FC 온라인", "스타크래프트", "던전앤파이터", "서든어택"],
        "50s": ["FC 온라인", "스타크래프트", "카트라이더", "동물의 숲"],
        "60s": ["동물의 숲", "닌텐도 스위치", "카트라이더", "스타크래프트"],
        "70s": ["닌텐도 스위치", "동물의 숲", "카트라이더"],
      },
    },
  },
  {
    id: "ent-6",
    slug: "boxoffice-expectation",
    channel: "entertainment",
    title: "영화 선호 지수",
    shortTitle: "영화 선호 지수",
    criteria: "개봉작·개봉 예정작의 예매율, 포털 검색, 평점. 반드시 실제 영화 제목",
    affiliateCategory: "빔프로젝터 · 홈시네마",
    queries: [
      "박스오피스 예매율",
      "CGV 예매 순위",
      "개봉 영화 관객수",
      "롯데시네마 차트",
      "개봉 예정 영화",
    ],
    focusKeyword: "박스오피스",
    supportKeyword: "영화 선호 지수",
    seeds: [
      "파묘",
      "범죄도시4",
      "베테랑2",
      "탈주",
      "파일럿",
      "핸섬가이즈",
      "위키드",
      "인사이드 아웃 2",
      "좀비딸",
      "F1 더 무비",
      "미키 17",
      "슈퍼맨",
      "캡틴 아메리카",
      "모아나 2",
      "무파사: 라이온 킹",
      "히트맨2",
      "그녀가 죽었다",
      "승부",
      "야당",
      "어쩔수가없다",
      "서울의 봄",
      "올드보이",
      "인터스텔라",
      "듄: 파트 2",
      "베놈: 라스트 댄스",
      "글래디에이터 II",
      "위키드 포 굿",
      "로보트 태권 V",
    ],
    unitLabel: "영화",
    rankGuidance:
      "반드시 실제 영화 제목만 반환하라. '영화 A', '영화 B', '한국 상업영화', '할리우드 대작' 같은 장르/플레이스홀더는 금지. 수집 보도에 제목이 있으면 그 제목을 쓰고, 없으면 최근 한국·할리우드 개봉작 제목을 추정하라. 10대는 애니메이션·슈퍼히어로, 50대 이상은 한국 상업영화·재개봉작 비중을 높여라.",
    demographicSeeds: {
      age: {
        "10s": ["인사이드 아웃 2", "모아나 2", "슈퍼맨", "캡틴 아메리카", "좀비딸", "위키드"],
        "20s": ["F1 더 무비", "미키 17", "위키드", "듄: 파트 2", "글래디에이터 II"],
        "50s": ["파묘", "범죄도시4", "베테랑2", "서울의 봄", "탈주"],
        "60s": ["서울의 봄", "파묘", "올드보이", "인터스텔라", "베테랑2"],
        "70s": ["올드보이", "인터스텔라", "서울의 봄", "로보트 태권 V"],
      },
    },
  },
  {
    id: "ent-10",
    slug: "entertain-youtuber-ranking",
    channel: "entertainment",
    title: "엔터 유튜버 랭킹",
    shortTitle: "엔터 유튜버 랭킹",
    criteria: "연예 이슈·방송 하이라이트·아이돌/배우 전문 유튜브 채널의 조회·구독·화제성",
    affiliateCategory: "유튜브 장비",
    queries: [
      "연예 유튜버",
      "아이돌 유튜브 채널",
      "방송 하이라이트 유튜브",
      "엔터 유튜브 구독자",
      "문명특급",
    ],
    focusKeyword: "엔터 유튜버",
    supportKeyword: "유튜브 랭킹",
    seeds: [
      "문명특급",
      "피식대학",
      "숏박스",
      "채널십오야",
      "딩고 프리스타일",
      "1theK",
      "워크맨",
      "이영지",
      "주우재",
      "헤이지니",
      "보라미유",
      "웃소",
      "디글",
      "아이돌플러스",
      "스브스케이팝",
      "달라스튜디오",
      "김용명",
      "노홍철",
      "풍자",
      "박준형",
      "곽튜브",
      "원지",
      "조나단",
      "띠예",
      "숏드",
      "해그워",
      "침착맨",
      "나영석",
    ],
    unitLabel: "채널",
    rankGuidance:
      "연예·방송·아이돌 전문 유튜브 채널명만 적어라. 재테크·게임 전문 채널은 넣지 마라. 10대는 아이돌·숏폼 예능, 30~40대는 나영석·워크맨·디글, 50대 이상은 박준형·풍자·디글 비중을 높여라.",
    demographicSeeds: {
      age: {
        "10s": ["이영지", "숏박스", "아이돌플러스", "딩고 프리스타일", "1theK", "숏드", "헤이지니"],
        "20s": ["피식대학", "문명특급", "채널십오야", "주우재", "곽튜브", "원지", "웃소"],
        "30s": ["워크맨", "나영석", "피식대학", "문명특급", "침착맨", "디글"],
        "40s": ["나영석", "워크맨", "디글", "박준형", "노홍철", "김용명"],
        "50s": ["박준형", "풍자", "디글", "나영석", "노홍철"],
        "60s": ["박준형", "풍자", "디글", "나영석"],
        "70s": ["박준형", "풍자", "디글"],
      },
    },
  },
  {
    id: "ent-7",
    slug: "shortform-meme-velocity",
    channel: "entertainment",
    title: "숏폼 밈 확산 속도 지수",
    shortTitle: "숏폼 밈",
    criteria: "틱톡, 릴스, 쇼츠 인기 사운드 및 챌린지 순위. 연령대별로 다른 밈 키워드",
    affiliateCategory: "짐벌 · 링라이트",
    queries: ["숏폼 챌린지 유행", "틱톡 인기 사운드", "릴스 밈", "쇼츠 유행어"],
    focusKeyword: "숏폼 밈",
    supportKeyword: "밈 확산",
    seeds: [
      "틱톡 댄스 챌린지",
      "릴스 중독 사운드",
      "급식체 밈",
      "학교 유행 포즈",
      "플러팅 챌린지",
      "연애 상담 밈",
      "퇴사각 릴스",
      "카공 브이로그",
      "육아 생존 밈",
      "직장인 월요병",
      "홈카페 릴스",
      "학부모 단톡 밈",
      "골프 숏폼",
      "위스키 토닉 릴스",
      "카톡 이모티콘 유행",
      "건강 쇼츠",
      "트로트 챌린지",
      "손주 영상 밈",
      "실버 유튜브 쇼츠",
      "건강 체조 릴스",
      "먹방 챌린지",
      "브이로그 밈",
      "유행어 밈",
      "사운드 밈",
      "포토부스 밈",
      "필터 챌린지",
      "립싱크 챌린지",
      "ASMR 쇼츠",
    ],
    unitLabel: "밈",
    rankGuidance:
      "연령 탭마다 밈 키워드가 달라야 한다. 10대=틱톡·급식체·학교 챌린지, 20대=연애·퇴사·카공, 30대=육아·직장, 40대=학부모·골프, 50대=카톡 이모티콘·건강 쇼츠·트로트 챌린지, 60~70대=손주 영상·실버 유튜브·건강 체조. 전 연령에 같은 댄스 챌린지만 반복하지 마라.",
    demographicSeeds: {
      age: {
        "10s": ["틱톡 댄스 챌린지", "릴스 중독 사운드", "급식체 밈", "학교 유행 포즈", "필터 챌린지", "립싱크 챌린지", "포토부스 밈"],
        "20s": ["플러팅 챌린지", "연애 상담 밈", "퇴사각 릴스", "카공 브이로그", "먹방 챌린지", "사운드 밈"],
        "30s": ["육아 생존 밈", "직장인 월요병", "홈카페 릴스", "먹방 챌린지", "브이로그 밈"],
        "40s": ["학부모 단톡 밈", "골프 숏폼", "위스키 토닉 릴스", "직장인 월요병", "홈카페 릴스"],
        "50s": ["카톡 이모티콘 유행", "건강 쇼츠", "트로트 챌린지", "유행어 밈", "ASMR 쇼츠"],
        "60s": ["손주 영상 밈", "실버 유튜브 쇼츠", "건강 체조 릴스", "트로트 챌린지", "건강 쇼츠"],
        "70s": ["실버 유튜브 쇼츠", "건강 체조 릴스", "손주 영상 밈", "ASMR 쇼츠", "트로트 챌린지"],
      },
    },
  },
  {
    id: "ent-8",
    slug: "realtime-webtoon-rank",
    channel: "entertainment",
    title: "실시간 웹툰 순위",
    shortTitle: "실시간 웹툰 순위",
    criteria: "네이버·카카오 웹툰 실시간 랭킹, 조회·댓글·원작 화제성",
    affiliateCategory: "이북리더기 · 독서대",
    queries: ["네이버웹툰 실시간 랭킹", "카카오웹툰 인기", "웹툰 원작 드라마", "웹툰 순위"],
    focusKeyword: "실시간 웹툰",
    supportKeyword: "웹툰 순위",
    seeds: [
      "나 혼자만 레벨업",
      "외모지상주의",
      "전지적 독자 시점",
      "김부장",
      "화산귀환",
      "재혼 황후",
      "여신강림",
      "싸움독학",
      "입학용병",
      "캐슬",
      "신의 탑",
      "호랑신과 억울한 도깨비",
      "이번 생도 잘 부탁해",
      "세기말 풋사과 보습학원",
      "내과 박원장",
      "연애혁명",
      "집이 없어",
      "독립일기",
      "쌉니다 천리마마트",
      "이두나!",
      "유미의 세포들",
      "치즈인더트랩",
      "여신강림 후속",
      "마루는 강쥐",
      "대학원 탈출일지",
      "무직전생",
      "나 혼자만 레벨업 리턴즈",
      "절대검감",
    ],
    unitLabel: "작품",
    rankGuidance:
      "실제 웹툰 작품명만 적어라. 10대는 학원·로맨스, 20~30대는 판타지·액션, 40대 이상은 드라마·일상물 비중을 높여라.",
    demographicSeeds: {
      age: {
        "10s": ["외모지상주의", "여신강림", "연애혁명", "싸움독학", "입학용병", "마루는 강쥐"],
        "20s": ["나 혼자만 레벨업", "전지적 독자 시점", "화산귀환", "재혼 황후", "캐슬"],
        "40s": ["김부장", "내과 박원장", "독립일기", "유미의 세포들"],
        "50s": ["독립일기", "유미의 세포들", "치즈인더트랩", "김부장"],
        "60s": ["독립일기", "마루는 강쥐", "유미의 세포들"],
        "70s": ["독립일기", "마루는 강쥐", "호랑신과 억울한 도깨비"],
      },
    },
  },
];

const BY_SLUG = new Map(BOARDS.map((board) => [board.slug, board]));

/** Old slugs that folded into a later board. */
export const BOARD_SLUG_ALIASES: Record<string, string> = {
  "us-stock-trend-index": "kospi-fomo-index",
  "entertainment-business": "kpop-fandom-power",
  "variety-hot-minute": "realtime-tv-ratings",
  "ticketing-competition": "performance-ticket-ranking",
  "travel-destination-index": "overseas-travel-ranking",
};

/** Where the 종합 tab sits among rail boards. Culture and others lead with 종합. */
export function compositeTabIndex(_channel: PostChannel): number {
  return 0;
}

export function resolveBoardSlug(slug: string): string {
  return BOARD_SLUG_ALIASES[slug] ?? slug;
}

export function getBoard(slug: string): BoardDefinition | undefined {
  return BY_SLUG.get(resolveBoardSlug(slug));
}

export function boardsForChannel(channel: PostChannel): BoardDefinition[] {
  return BOARDS.filter((board) => board.channel === channel);
}

export function isDeskBoard(board: Pick<BoardDefinition, "deskKind">): boolean {
  return Boolean(board.deskKind);
}

export function isRailBoard(board: Pick<BoardDefinition, "railHidden">): boolean {
  return !board.railHidden;
}

/** Category rail, 종합 heatmap, and sibling links — hides retired politics tabs. */
export function menuBoardsForChannel(channel: PostChannel): BoardDefinition[] {
  return boardsForChannel(channel).filter(isRailBoard).filter((board) => !isRetiredPoliticsBoard(board.slug));
}

export function rankingBoardsForChannel(channel: PostChannel): BoardDefinition[] {
  return menuBoardsForChannel(channel).filter((board) => !isDeskBoard(board));
}

export function boardPath(slug: string): string {
  return `/board/${resolveBoardSlug(slug)}`;
}

export function categoryBoardPath(channel: PostChannel): string {
  return `/category/${channel}`;
}
